In [7]:
import numpy as np
x = np.array([[1,2,3],[4,6,5]])
print(x[0,1])
print(x)
x[0,0] = 3
print(x)

2
[[1 2 3]
 [4 6 5]]
[[3 2 3]
 [4 6 5]]


In [9]:
print(x.shape)

(2, 3)


In [11]:
print(x.dtype)

int32


In [13]:
a = np.zeros((2,2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [16]:
b = np.ones((2,2))
print(b)

[[ 1.  1.]
 [ 1.  1.]]


In [18]:
c = np.full((3,3),7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [20]:
d = np.eye(3)
print(d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [21]:
e = np.random.random((3,3))
print(e)

[[ 0.73305706  0.60538468  0.0954245 ]
 [ 0.62688837  0.3145298   0.86746526]
 [ 0.95277252  0.01544969  0.84770722]]


In [26]:
f = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f)
i = f[:2,1:3]
print(i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [33]:
print(f[[0,1,2],[1,3,3]])
print(np.array([f[0,1],f[1,3],f[2,3]]))

[ 2  8 12]
[ 2  8 12]
